import { useMemo, useState } from "react";
import {
    AlertTriangle,
    BadgeCheck,
    ChevronDown,
    CircleDot,
    LayoutGrid,
    Menu,
    MessageSquareText,
    ShieldCheck,
    TrendingUp,
    Activity,
    Zap,
} from "lucide-react";
import { Sidebar } from "@/components/Sidebar";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Tabs } from "@/components/ui/tabs";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { DashboardHeader } from "@/pages/Dashboard/DashboardHeader";
import { useToast } from "@/hooks/use-toast";

type InsightCategory =
    | "all"
    | "fraud"
    | "vendor"
    | "revenue"
    | "platform"
    | "moderation";

type Insight = {
    id: string;
    category: Exclude<InsightCategory, "all">;
    label: string;
    title: string;
    confidencePct: number;
    generatedAt: string;
    listTime: string;
    listPct: number;
    evidence: string[];
    affectedVendors: string[];
    recommendationTitle: string;
    recommendationBody: string;
    potentialImpactLabel: string;
    whyThisBody: string;
    accent: {
        border: string;
        bg: string;
        pillBg: string;
        pillText: string;
        iconBg: string;
        iconText: string;
    };
    icon: "fraud" | "vendor" | "revenue" | "platform" | "moderation";
};

const INSIGHTS_SEED: Insight[] = [
    {
        id: "fraud-1",
        category: "fraud",
        label: "FRAUD DETECTION",
        title: "Suspicious receipt patterns detected across 14 vendors",
        confidencePct: 92,
        generatedAt: "12/29/2024, 9:20:00 AM",
        listTime: "9:20:00 AM",
        listPct: 92,
        evidence: [
            "Repeated identical receipt formats from different stores",
            "Unusual discount patterns exceeding 85%",
            "Timestamp anomalies in transaction records",
            "Geographic inconsistencies in purchase locations",
        ],
        affectedVendors: [
            "QuickMart Store",
            "DealZone Express",
            "TechWorld Shop",
            "BargainBay Plus",
        ],
        recommendationTitle: "AI Recommendation",
        recommendationBody:
            "Review affected vendors and consider temporary restrictions.",
        potentialImpactLabel: "Estimated $45,000 in fraudulent transactions",
        whyThisBody:
            "This insight is generated by analyzing receipt patterns, transaction timestamps, and comparing against known fraud signatures in our data.",
        accent: {
            border: "border-[#ef4343]",
            bg: "bg-[linear-gradient(90deg,rgba(239,67,67,0.06)_0%,rgba(239,67,67,0)_100%)]",
            pillBg: "bg-[#ffe7e7]",
            pillText: "text-[#ef4343]",
            iconBg: "bg-[#ffe7e7]",
            iconText: "text-[#ef4343]",
        },
        icon: "fraud",
    },
    {
        id: "vendor-1",
        category: "vendor",
        label: "VENDOR RISK",
        title: "Vendor 'AutoLux Parts' risk score increased to 72/100",
        confidencePct: 78,
        generatedAt: "12/29/2024, 8:45:00 AM",
        listTime: "8:45:00 AM",
        listPct: 78,
        evidence: [
            "Higher-than-usual refund rate in last 7 days",
            "Multiple pricing anomalies across categories",
            "Inconsistent payout account changes",
        ],
        affectedVendors: ["AutoLux Parts"],
        recommendationTitle: "AI Recommendation",
        recommendationBody:
            "Perform a vendor compliance review and monitor refund spikes.",
        potentialImpactLabel: "Increased chargeback risk",
        whyThisBody:
            "This insight is generated by correlating refund signals, payout changes, and customer support complaints.",
        accent: {
            border: "border-[#f59f0a]",
            bg: "bg-[linear-gradient(90deg,rgba(245,159,10,0.06)_0%,rgba(245,159,10,0)_100%)]",
            pillBg: "bg-[#fff0d6]",
            pillText: "text-[#f59f0a]",
            iconBg: "bg-[#fff0d6]",
            iconText: "text-[#f59f0a]",
        },
        icon: "vendor",
    },
    {
        id: "revenue-1",
        category: "revenue",
        label: "REVENUE INTELLIGENCE",
        title: "Raising posting fee by 5% could increase MRR by ~$24k",
        confidencePct: 71,
        generatedAt: "12/29/2024, 8:00:00 AM",
        listTime: "8:00:00 AM",
        listPct: 71,
        evidence: [
            "High adoption likelihood from top vendors",
            "Low elasticity observed in recent fee tests",
            "Projected churn increase below 0.4%",
        ],
        affectedVendors: ["Top Vendors"],
        recommendationTitle: "AI Recommendation",
        recommendationBody: "Simulate pricing change and roll out gradually.",
        potentialImpactLabel: "+$24,000 MRR (estimated)",
        whyThisBody:
            "This insight is generated by modeling historical pricing changes and forecasting vendor retention.",
        accent: {
            border: "border-[#16a249]",
            bg: "bg-[linear-gradient(90deg,rgba(22,162,73,0.06)_0%,rgba(22,162,73,0)_100%)]",
            pillBg: "bg-[#e6f6ec]",
            pillText: "text-[#16a249]",
            iconBg: "bg-[#e6f6ec]",
            iconText: "text-[#16a249]",
        },
        icon: "revenue",
    },
    {
        id: "platform-1",
        category: "platform",
        label: "PLATFORM HEALTH",
        title: "User engagement up 18% following new feature release",
        confidencePct: 95,
        generatedAt: "12/29/2024, 7:30:00 AM",
        listTime: "7:30:00 AM",
        listPct: 95,
        evidence: [
            "Session duration increased 9%",
            "Daily active users increased 18%",
            "Feature adoption reached 42% in 48 hours",
        ],
        affectedVendors: ["All"],
        recommendationTitle: "AI Recommendation",
        recommendationBody:
            "Keep feature promoted and monitor retention cohorts.",
        potentialImpactLabel: "Improved retention",
        whyThisBody:
            "This insight is generated by analyzing event streams and cohort-level retention deltas.",
        accent: {
            border: "border-[#2b73f7]",
            bg: "bg-[linear-gradient(90deg,rgba(43,115,247,0.06)_0%,rgba(43,115,247,0)_100%)]",
            pillBg: "bg-[#e9f0ff]",
            pillText: "text-[#2b73f7]",
            iconBg: "bg-[#e9f0ff]",
            iconText: "text-[#2b73f7]",
        },
        icon: "platform",
    },
    {
        id: "moderation-1",
        category: "moderation",
        label: "MODERATION INTELLIGENCE",
        title: "Emerging scam pattern detected in Electronics category",
        confidencePct: 84,
        generatedAt: "12/29/2024, 6:15:00 AM",
        listTime: "6:15:00 AM",
        listPct: 84,
        evidence: [
            "High similarity across newly posted listings",
            "Unusual external link frequency",
            "Repeat offender accounts detected",
        ],
        affectedVendors: ["Electronics"],
        recommendationTitle: "AI Recommendation",
        recommendationBody:
            "Apply stricter auto-moderation rules for this category.",
        potentialImpactLabel: "Reduced scam exposure",
        whyThisBody:
            "This insight is generated by clustering listing content and detecting repeat offender behavior.",
        accent: {
            border: "border-[#7a5cff]",
            bg: "bg-[linear-gradient(90deg,rgba(122,92,255,0.06)_0%,rgba(122,92,255,0)_100%)]",
            pillBg: "bg-[#efeaff]",
            pillText: "text-[#7a5cff]",
            iconBg: "bg-[#efeaff]",
            iconText: "text-[#7a5cff]",
        },
        icon: "moderation",
    },
];

function getIcon(kind: Insight["icon"]) {
    switch (kind) {
        case "fraud":
            return AlertTriangle;
        case "vendor":
            return ShieldCheck;
        case "revenue":
            return TrendingUp;
        case "platform":
            return Activity;
        case "moderation":
            return MessageSquareText;
        default:
            return Zap;
    }
}

export const AIIntelligenceCenterScreen = (): JSX.Element => {
    const { toast } = useToast();

    const [tab, setTab] = useState<InsightCategory>("all");
    const [search, setSearch] = useState("");
    const [items, setItems] = useState<Insight[]>(INSIGHTS_SEED);
    const [selectedId, setSelectedId] = useState<string>(INSIGHTS_SEED[0]?.id);

    const tabItems = useMemo(
        () => [
            {
                value: "all" as const,
                label: "All Insights",
                icon: LayoutGrid,
            },
            {
                value: "fraud" as const,
                label: "Fraud & Abuse",
                icon: AlertTriangle,
            },
            {
                value: "vendor" as const,
                label: "Vendor Risk",
                icon: ShieldCheck,
            },
            {
                value: "revenue" as const,
                label: "Revenue",
                icon: TrendingUp,
            },
            {
                value: "platform" as const,
                label: "Platform Health",
                icon: Activity,
            },
            {
                value: "moderation" as const,
                label: "Moderation",
                icon: CircleDot,
            },
        ],
        [],
    );

    const filtered = useMemo(() => {
        const query = search.trim().toLowerCase();
        return items
            .filter((i) => (tab === "all" ? true : i.category === tab))
            .filter((i) => {
                if (!query) return true;
                return (
                    i.title.toLowerCase().includes(query) ||
                    i.label.toLowerCase().includes(query) ||
                    i.affectedVendors.join(" ").toLowerCase().includes(query)
                );
            });
    }, [items, search, tab]);

    const selected = useMemo(() => {
        const byId = items.find((i) => i.id === selectedId);
        if (byId) return byId;
        return filtered[0] ?? items[0];
    }, [filtered, items, selectedId]);

    const handleDismiss = () => {
        if (!selected) return;
        setItems((prev) => prev.filter((i) => i.id !== selected.id));
        toast({
            title: "Dismissed",
            description: "Insight has been dismissed.",
        });
        setTimeout(() => {
            setSelectedId((prev) => {
                if (prev !== selected.id) return prev;
                const next = filtered.find((i) => i.id !== selected.id);
                return next?.id ?? "";
            });
        }, 0);
    };

    const handleReportFalsePositive = () => {
        if (!selected) return;
        toast({
            title: "Reported",
            description:
                "Thanks. We’ll use this feedback to improve detection.",
        });
    };

    const handleViewVendors = () => {
        if (!selected) return;
        toast({
            title: "View Vendors",
            description: "Wire this action to your vendors page when ready.",
        });
    };

    return (
        <div className="bg-[#F5F6FA] w-full h-screen overflow-hidden">
            <div className="hidden lg:block fixed inset-y-0 left-0 w-[292px] z-40">
                <Sidebar className="w-[280px]" variant="desktop" />
            </div>

            <main className="h-screen overflow-y-auto no-scrollbar lg:pl-[292px]">
                <div className="flex flex-col items-start gap-[14px] p-[16px] sm:p-[24px] overflow-x-hidden">
                    <div className="w-full flex items-center justify-between lg:hidden">
                        <Sheet>
                            <SheetTrigger asChild>
                                <Button
                                    variant="outline"
                                    className="bg-white border-[#e0ebe5]"
                                >
                                    <Menu className="h-5 w-5" />
                                </Button>
                            </SheetTrigger>
                            <SheetContent
                                side="left"
                                className="p-0 bg-transparent border-0"
                            >
                                <Sidebar
                                    className="w-[280px]"
                                    variant="drawer"
                                />
                            </SheetContent>
                        </Sheet>
                        <div className="text-[#222f36] font-semibold text-lg">
                            AI Intelligence Center
                        </div>
                        <div className="w-10" />
                    </div>

                    <DashboardHeader
                        title="AI Intelligence Center"
                        description="Central command for AI-powered platform insights"
                        onSearch={(q) => setSearch(q)}
                    />

                    <div className="w-full">
                        <Tabs value={tab} onValueChange={() => {}}>
                            <div className="w-full flex items-center gap-3 flex-wrap mt-5">
                                {tabItems.map((t) => {
                                    const active = tab === t.value;
                                    const Icon = t.icon;
                                    return (
                                        <button
                                            key={t.value}
                                            type="button"
                                            onClick={() => setTab(t.value)}
                                            className={
                                                "h-[28px] rounded-[7px] p-4  flex items-center gap-2 text-[12px] font-medium transition-colors border " +
                                                (active
                                                    ? "bg-[#62a230] border-[#62a230] text-white"
                                                    : "bg-transparent border-transparent text-[#6b7681] hover:bg-white/70")
                                            }
                                        >
                                            <Icon
                                                className={
                                                    "w-3.5 h-3.5 " +
                                                    (active
                                                        ? "text-white"
                                                        : "text-[#9aa3ad]")
                                                }
                                            />
                                            {t.label}
                                        </button>
                                    );
                                })}
                            </div>
                        </Tabs>
                    </div>

                    <div className="w-full grid grid-cols-1 xl:grid-cols-[360px_1fr] gap-4">
                        <div className="space-y-3">
                            {filtered.map((it) => {
                                const isActive = selected?.id === it.id;
                                const Icon = getIcon(it.icon);
                                return (
                                    <button
                                        key={it.id}
                                        type="button"
                                        onClick={() => setSelectedId(it.id)}
                                        className="w-full text-left"
                                    >
                                        <Card
                                            className={
                                                "rounded-[14px] border border-[#edf1f3] bg-white shadow-[0px_1px_3px_#00000005] overflow-hidden " +
                                                (isActive
                                                    ? "ring-2 ring-[#62a230]/30"
                                                    : "")
                                            }
                                        >
                                            <div
                                                className={
                                                    "border-l-[5px] " +
                                                    it.accent.border +
                                                    " " +
                                                    it.accent.bg +
                                                    " px-4 py-3"
                                                }
                                            >
                                                <div className="flex items-center justify-between">
                                                    <div className="flex items-center gap-2">
                                                        <span className="inline-flex items-center gap-1 rounded-full bg-white/80 border border-white/80 px-2 py-1">
                                                            <Icon
                                                                className={
                                                                    "w-3.5 h-3.5 " +
                                                                    it.accent
                                                                        .iconText
                                                                }
                                                            />
                                                            <span
                                                                className={
                                                                    "text-[10px] font-semibold tracking-[0.6px] " +
                                                                    it.accent
                                                                        .pillText
                                                                }
                                                            >
                                                                {it.label}
                                                            </span>
                                                        </span>
                                                    </div>
                                                    <div className="text-[11px] text-[#7b848f] font-medium">
                                                        {it.listPct}%
                                                    </div>
                                                </div>

                                                <div className="mt-2 text-[13px] font-semibold text-[#222f36] leading-[18px]">
                                                    {it.title}
                                                </div>

                                                <div className="mt-2 flex items-center justify-between">
                                                    <div className="text-[11px] text-[#7b848f]">
                                                        {it.listTime}
                                                    </div>
                                                    <div className="flex items-center gap-1 text-[#7b848f]">
                                                        <ChevronDown className="w-4 h-4" />
                                                    </div>
                                                </div>
                                            </div>
                                        </Card>
                                    </button>
                                );
                            })}

                            {filtered.length === 0 ? (
                                <div className="text-sm text-[#7b848f] px-2">
                                    No insights match your filters.
                                </div>
                            ) : null}
                        </div>

                        <div>
                            <Card className="rounded-[16px] border-0 bg-white shadow-[0px_1px_3px_#00000005,0px_6px_10px_#b1b1b114] overflow-hidden">
                                {selected ? (
                                    <div>
                                        <div className="px-5 sm:px-6 py-5 bg-[#fff3f3] border-b border-[#f1e2e2]">
                                            <div className="flex items-start justify-between gap-4">
                                                <div>
                                                    <div className="flex items-center gap-2">
                                                        <span
                                                            className={
                                                                "inline-flex items-center rounded-full px-3 py-1 text-[10px] font-semibold tracking-[0.6px] bg-white/80 border border-white/80 " +
                                                                selected.accent
                                                                    .pillText
                                                            }
                                                        >
                                                            {selected.label}
                                                        </span>
                                                    </div>

                                                    <div className="mt-3 text-[16px] font-semibold text-[#222f36]">
                                                        {selected.title}
                                                    </div>

                                                    <div className="mt-2 text-[11px] text-[#7b848f]">
                                                        Confidence:{" "}
                                                        {selected.confidencePct}
                                                        %
                                                        <span className="mx-1">
                                                            •
                                                        </span>
                                                        Generated:{" "}
                                                        {selected.generatedAt}
                                                    </div>
                                                </div>

                                                <div className="w-9 h-9 rounded-xl bg-white/70 border border-white/70 flex items-center justify-center text-[#62a230]">
                                                    <Zap className="w-4.5 h-4.5" />
                                                </div>
                                            </div>
                                        </div>

                                        <div className="p-5 sm:p-6">
                                            <div className="flex items-center gap-2 text-[#222f36] font-semibold text-[13px]">
                                                <BadgeCheck className="w-4 h-4 text-[#62a230]" />
                                                Evidence & Findings
                                            </div>

                                            <div className="mt-3 space-y-3">
                                                {selected.evidence.map((e) => (
                                                    <div
                                                        key={e}
                                                        className="flex items-start gap-3"
                                                    >
                                                        <span className="w-2.5 h-2.5 rounded-full bg-[#62a230] mt-1.5" />
                                                        <div className="text-[12px] text-[#222f36] leading-[18px]">
                                                            {e}
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>

                                            <div className="mt-5">
                                                <div className="text-[12px] font-semibold text-[#222f36]">
                                                    Affected Vendors
                                                </div>
                                                <div className="mt-2 flex flex-wrap gap-2">
                                                    {selected.affectedVendors.map(
                                                        (v) => (
                                                            <Badge
                                                                key={v}
                                                                variant="secondary"
                                                                className="rounded-full bg-[#ffe7e7] text-[#ef4343] border-0 text-[11px] font-medium"
                                                            >
                                                                {v}
                                                            </Badge>
                                                        ),
                                                    )}
                                                </div>
                                            </div>

                                            <div className="mt-5 rounded-[12px] border border-[#cfe7d5] bg-[#f3fbf6] p-4">
                                                <div className="text-[12px] font-semibold text-[#222f36]">
                                                    {
                                                        selected.recommendationTitle
                                                    }
                                                </div>
                                                <div className="mt-1 text-[11px] text-[#7b848f]">
                                                    {
                                                        selected.recommendationBody
                                                    }
                                                </div>

                                                <div className="mt-3 flex items-center gap-2 text-[11px]">
                                                    <span className="text-[#7b848f]">
                                                        Potential Impact:
                                                    </span>
                                                    <span className="rounded-full bg-[#e6f6ec] text-[#16a249] px-2 py-0.5 font-semibold">
                                                        {
                                                            selected.potentialImpactLabel
                                                        }
                                                    </span>
                                                </div>
                                            </div>

                                            <div className="mt-5 rounded-[12px] border border-[#edf1f3] bg-white p-4">
                                                <div className="text-[12px] font-semibold text-[#222f36]">
                                                    Why am I seeing this?
                                                </div>
                                                <div className="mt-1 text-[11px] text-[#7b848f] leading-[17px]">
                                                    {selected.whyThisBody}
                                                </div>
                                            </div>

                                            <div className="mt-5 border-t border-[#edf1f3] pt-4 flex items-center gap-2">
                                                <Button
                                                    onClick={handleViewVendors}
                                                    className="h-9 rounded-[10px] bg-[#62a230] hover:bg-[#4e8b22] text-white text-[12px]"
                                                >
                                                    View Vendors
                                                </Button>
                                                <Button
                                                    onClick={handleDismiss}
                                                    variant="outline"
                                                    className="h-9 rounded-[10px] bg-white border border-[#dfe6e1] text-[#222f36] text-[12px]"
                                                >
                                                    Dismiss
                                                </Button>
                                                <Button
                                                    onClick={
                                                        handleReportFalsePositive
                                                    }
                                                    variant="outline"
                                                    className="h-9 rounded-[10px] bg-white border border-[#dfe6e1] text-[#222f36] text-[12px]"
                                                >
                                                    Report False Positive
                                                </Button>
                                            </div>

                                            <div className="mt-4 text-[10px] text-[#b0b6bf]">
                                                AI recommendations are advisory
                                                only. Always validate with admin
                                                policy/team.
                                            </div>
                                        </div>
                                    </div>
                                ) : (
                                    <div className="p-6 text-sm text-[#7b848f]">
                                        No insight selected.
                                    </div>
                                )}
                            </Card>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
};
